//
// Code auto-generated by initpackage (XSPEC12 local 
// model package code generator).  Do not edit.
// Package: absmodel
// Function body: absmodelFunctionMap.cxx

#include    "absmodelFunctionMap.h"

#include    <XSFunctions/Utilities/XSModelFunction.h>
#include    <XSFunctions/Utilities/XSCall.h>

void 
createabsmodelFunctionMap()
{


	XSModelFunction::addFunctionPointer( "tbnew",      new XSCall<xsccCall>(tbnew) );
	XSModelFunction::addFunctionPointer( "tbnew_feo",  new XSCall<xsccCall>(tbvabsfeo) );
	XSModelFunction::addFunctionPointer( "tbnew_gas",  new XSCall<xsccCall>(tbgas) );
	XSModelFunction::addFunctionPointer( "tbnew_pcf",  new XSCall<xsccCall>(tbvabspcf) );
	XSModelFunction::addFunctionPointer( "tbnew_rel",  new XSCall<xsccCall>(tbvabsrel) );

}
