//
// Code auto-generated by initpackage (XSPEC12 local 
// model package code generator).  Do not edit.
// Package: absmodel
// Function header: absmodelFunctionMap.h

#ifndef    FUNCTIONMAP_H
#define    FUNCTIONMAP_H

#include    <XSFunctions/Utilities/funcType.h>

class    XSCallBase;

void  createabsmodelFunctionMap();

extern "C"  {


	xsccCall     tbnew;
	xsccCall     tbvabsfeo;
	xsccCall     tbgas;
	xsccCall     tbvabspcf;
	xsccCall     tbvabsrel;
}


#endif
