//
// Code auto-generated by initpackage (XSPEC12 local model package 
// code generator).  Do not edit
// Package: absmodel Created :
// Initializer: absmodel.cxx

#include <XSUser/UserInterface/xstcl.h>

#include  "absmodelFunctionMap.h"
#include  <XSFunctions/Utilities/XSCall.h>
#include  <XSFunctions/Utilities/XSModelFunction.h>

extern "C" int Absmodel_Init(Tcl_Interp* tclInterp);
extern "C" int Absmodel_SafeInit(Tcl_Interp* tclInterp);

int Absmodel_Init(Tcl_Interp* tclInterp)
{
        return Absmodel_SafeInit(tclInterp);
}

int Absmodel_SafeInit(Tcl_Interp* tclInterp)
{

        char PACKAGE[] = "absmodel";
        char VERSION[] = "1.0";
        Tcl_PkgProvide(tclInterp, PACKAGE, VERSION);
        XSModelFunction::updateComponentList
              ("/Users/zachsumners/Desktop/Research/Chandra/Chandra_SgrA-_FlarePipelineNoGithub/FluxCalibration/absmodel/lmodel_tbnew.dat");
        createabsmodelFunctionMap();
        return TCL_OK;

}

